version: '2.0'
services:
  bgg:
    build: .
    ports:
      - 9000:80
    links:
      - rabbitmq
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672