version: 2
jobs:
  build:
    working_directory: ~/bgg
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: pwd
          command: pwd
      - run:
          name: Docker Build
          command: docker build -t="bgg" .
      - run:
          name: ls in docker
          command: docker run -v /root/bgg/:/opt/app/ bgg ls
      - run:
          name: ls in docker2
          command: docker run -v ~/bgg:/opt/app bgg ls
      - run:
          name: npm install
          command: docker run -v ~/bgg:/opt/app bgg npm install
      - run:
          name: Build prod
          command: docker run -v ~/bgg:/opt/app bgg npm run build-prod
      - run:
          name: Add aws cli dependencies
          command: |
            apk add --update python python-dev py-pip build-base libffi-dev openssl-dev
      - run:
          name: Add aws cli
          command: |
            pip install awscli
      - deploy:
          name: Push website to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              aws s3 sync ~/bgg/public/ s3://bgg.theahstudios.com/ --delete
            fi